server:
  port: 10010


spring:
  cloud:
    stream:
      kafka:
        binder:
#          brokers: 192.168.0.200:9092
          brokers: 127.0.0.1:9092
      default-binder: kafka
      bindings:
        user_register:
          destination: test_topic_02
          binder: kafka


