server:
  port: 10010


spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.0.200:9092
      default-binder: kafka
      bindings:
        msg_output:
          destination: test_topic_01
          binder: kafka


