server:
  port: 10010

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.0.200:9092
          zk-nodes: 192.168.0.200:2181
      bindings:
        test-binding:
          destination: login-user

