
server:
  port: 10010

jwt:
  key:
    rsa:
      public:
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCm0jZiLVzkFOWGDm54iMyiQz9BYHZKKDc6KVO8
        c7ZUJpprar1313A9WDEYt0scz7AZ1/uzjrxdu0D/zNgKFDx9lXTbbm6AcXCpQL/TmNQLiWb+OLYU
        ZL8i06aX7Oapo+qba8i/TXdVtdycBoKw8hIgTGfpOwfWjGpuPzj8IXfVmwIDAQAB
      private:
        MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAKbSNmItXOQU5YYObniIzKJDP0Fg
        dkooNzopU7xztlQmmmtqvXfXcD1YMRi3SxzPsBnX+7OOvF27QP/M2AoUPH2VdNtuboBxcKlAv9OY
        1AuJZv44thRkvyLTppfs5qmj6ptryL9Nd1W13JwGgrDyEiBMZ+k7B9aMam4/OPwhd9WbAgMBAAEC
        gYBfugr5BXzjaNZYudlMk3uRtTMMKfVXEoK2flaNsnyzBz/fWe4FYfwHR59Mxol0q/0qp1TJMaQH
        yVdAMmTaS8h1faxoXtPBIttdV+UNTmprg5iTXfB5wVTXmN3Ti0rGaX4RL/KUv9lbInH9z55OOOvs
        PzcJsgZyZQUBQ3ydNRca2QJBAOUBa2lx7PzlBa0CwAWpr/FOa2Q41Uyli8EWjNQcSXJ+78gxX7vQ
        g+ssmgo1MtDyI+XGA++aAwIHGZbL1ndSZ5cCQQC6fElkwcL8b1+6QFNXiS7kDrJNoA3RXKDbQ7l7
        5t23f+WffrL5pSpa91iOUTlhqdaZbtQO6x/Yute6YL1WveKdAkEArcSK/aMd4bPiv6pDjMh6og8Q
        PCdH6vX++tAiolyoesHJLs4QR5JsV0orxK0jVxs1lAfSOsBRoftDNoKLxVT5FwJADeRIS1srvUZG
        qUc1biXn+lEl8yZjIR93VB4daR9vkMXUQydbCcHF//TBAgkG70GJnPBml53oR2rTuyyNrjKC+QJA
        NPlwPWDPQNqVWPFpUE0D6+7QPOVSsn7HbIT6manM9WuL16xEAjl7AuBBTde4nWEMzNGoBOHK5E1a
        +OIKNA6rnw==
